### ISSUE TITLE
关于Faster RCNN的一些细节问题.

### ISSUE THREAD

**Issue by z1069614715** [bubbliiiing/faster-rcnn-pytorch#161]
B导你好，我想问问在ProposalTargetCreator中
![image](https://user-images.githubusercontent.com/45996119/216208961-c501d0dd-3f18-4088-bb09-f73a540424a9.png)
为什么要把roi建议框和bbox进行concat得到新的roi建议框？

**Comment by bubbliiiing** [comment]
目的是为了训练后面的网络，多添加一些建议框于训练

**Comment by z1069614715** [comment]
感谢！
