### ISSUE TITLE
东拼西凑的代码 结构真乱

### ISSUE THREAD

**Issue by chnzhero** [bubbliiiing/faster-rcnn-pytorch#19]

**Comment by bubbliiiing** [comment]
不好意思污了你的眼睛

**Comment by Yu-Chengwei** [comment]
说话真不客观，我找了很多TF2版本的RCNN，有的跑不起，有的要改的太多。
up主这份我就改了几个路径，安了两个包就跑起来了，结构已经很简洁了。

**Comment by chnzhero** [comment]
> 说话真不客观，我找了很多TF2版本的RCNN，有的跑不起，有的要改的太多。
> up主这份我就改了几个路径，安了两个包就跑起来了，结构已经很简洁了。

如果你只是想跑起来，那你说的确实没问题。

**Comment by bubbliiiing** [comment]
> 说话真不客观，我找了很多TF2版本的RCNN，有的跑不起，有的要改的太多。
> up主这份我就改了几个路径，安了两个包就跑起来了，结构已经很简洁了。

emm这个楼不回复了吧，每个人习惯不一样，没必要，我的库的格式尽量都保持一致，用起来方便
TF2的库我有上传一个，你可以看看（虽然batch还是等于1）。

**Comment by liaojiacai** [comment]
我觉得写得很清楚了，我转完数据，改改就可以跑起来了

**Comment by bubbliiiing** [comment]
我Close了兄弟
