### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for FasterRCNN:

### ISSUE THREAD

**Issue by floatGray** [bubbliiiing/faster-rcnn-pytorch#2]
训练出来的.pth无法加载，参数不匹配
详细报错：
Traceback (most recent call last):
  File "/home/floatgray/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e3285b8876a2>", line 1, in <module>
    runfile('/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/video.py', wdir='/home/floatgray/helmet_detection/faster-rcnn-pytorch-master')
  File "/home/floatgray/文档/pycharm-professional-2019.3/pycharm-2019.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/floatgray/文档/pycharm-professional-2019.3/pycharm-2019.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/video.py", line 9, in <module>
    frcnn = FRCNN()
  File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/frcnn.py", line 37, in __init__
    self.generate()
  File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/frcnn.py", line 61, in generate
    self.model.load_state_dict(torch.load(self.model_path))
  File "/home/floatgray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FasterRCNN:
	size mismatch for head.cls_loc.weight: copying a param with shape torch.Size([84, 2048]) from checkpoint, the shape in current model is torch.Size([12, 2048]).
	size mismatch for head.cls_loc.bias: copying a param with shape torch.Size([84]) from checkpoint, the shape in current model is torch.Size([12]).
	size mismatch for head.score.weight: copying a param with shape torch.Size([21, 2048]) from checkpoint, the shape in current model is torch.Size([3, 2048]).
	size mismatch for head.score.bias: copying a param with shape torch.Size([21]) from checkpoint, the shape in current model is torch.Size([3]).

**Comment by floatGray** [comment]
训练的是两个种类的检测，该改变的都改变了

**Comment by floatGray** [comment]
训练一切正常

**Comment by floatGray** [comment]
重新训练之后有报错：
`Traceback (most recent call last):
  File "/home/floatgray/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e3285b8876a2>", line 1, in <module>
    runfile('/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/video.py', wdir='/home/floatgray/helmet_detection/faster-rcnn-pytorch-master')
  File "/home/floatgray/文档/pycharm-professional-2019.3/pycharm-2019.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/floatgray/文档/pycharm-professional-2019.3/pycharm-2019.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/video.py", line 23, in <module>
    frame = np.array(frcnn.detect_image(frame))
  File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/frcnn.py", line 96, in detect_image
    score_thresh=self.confidence)
  File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/utils/utils.py", line 105, in forward
    cls_bbox[:, 3] = (cls_bbox[:, 3]).clamp(min=0, max=height)
IndexError: index 3 is out of bounds for dimension 1 with size 3`

**Comment by lyd953621450** [comment]
> 重新训练之后有报错：
> `Traceback (most recent call last): File "/home/floatgray/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code exec(code_obj, self.user_global_ns, self.user_ns) File "<ipython-input-2-e3285b8876a2>", line 1, in <module> runfile('/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/video.py', wdir='/home/floatgray/helmet_detection/faster-rcnn-pytorch-master') File "/home/floatgray/文档/pycharm-professional-2019.3/pycharm-2019.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile pydev_imports.execfile(filename, global_vars, local_vars) # execute the script File "/home/floatgray/文档/pycharm-professional-2019.3/pycharm-2019.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile exec(compile(contents+"\n", file, 'exec'), glob, loc) File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/video.py", line 23, in <module> frame = np.array(frcnn.detect_image(frame)) File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/frcnn.py", line 96, in detect_image score_thresh=self.confidence) File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/utils/utils.py", line 105, in forward cls_bbox[:, 3] = (cls_bbox[:, 3]).clamp(min=0, max=height) IndexError: index 3 is out of bounds for dimension 1 with size 3`

老哥，我存在的问题和你一样，你解决了吗？

**Comment by lyd953621450** [comment]
> 重新训练之后有报错：
> `Traceback (most recent call last): File "/home/floatgray/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code exec(code_obj, self.user_global_ns, self.user_ns) File "<ipython-input-2-e3285b8876a2>", line 1, in <module> runfile('/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/video.py', wdir='/home/floatgray/helmet_detection/faster-rcnn-pytorch-master') File "/home/floatgray/文档/pycharm-professional-2019.3/pycharm-2019.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile pydev_imports.execfile(filename, global_vars, local_vars) # execute the script File "/home/floatgray/文档/pycharm-professional-2019.3/pycharm-2019.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile exec(compile(contents+"\n", file, 'exec'), glob, loc) File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/video.py", line 23, in <module> frame = np.array(frcnn.detect_image(frame)) File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/frcnn.py", line 96, in detect_image score_thresh=self.confidence) File "/home/floatgray/helmet_detection/faster-rcnn-pytorch-master/utils/utils.py", line 105, in forward cls_bbox[:, 3] = (cls_bbox[:, 3]).clamp(min=0, max=height) IndexError: index 3 is out of bounds for dimension 1 with size 3`

       cls_bbox【..., 0】 = (cls_bbox【..., 0】).clamp(min=0, max=width)
        cls_bbox【..., 2】 = (cls_bbox【..., 2】).clamp(min=0, max=width)
        cls_bbox【..., 1】 = (cls_bbox【..., 1】).clamp(min=0, max=height)
        cls_bbox【..., 3】 = (cls_bbox【..., 3】).clamp(min=0, max=height)
修改成这样
up给的解决办法，我的可以预测了，你也试试看吧。
