### ISSUE TITLE
anchor.py中anchor生成问题

### ISSUE THREAD

**Issue by qiushenjie** [bubbliiiing/faster-rcnn-pytorch#26]
请教个问题
https://github.com/bubbliiiing/faster-rcnn-pytorch/blob/0cc7562a0bb92f911d840e16e9324134713ff779/utils/anchors.py#L31
前面通过generate_anchor_base()生成的anchor_base[0, :]的四个值对应的是h, w, h, w
_enumerate_shifted_anchor()中shift[0, :]的四个值对应的是w, h, w, h
那么anchor_base和shift相加生成的anchor[0, :]的四个值分别对应的是什么?
从后面的代码中看起是w, h, w, h

**Comment by bubbliiiing** [comment]
我看了看，应该是w,h,w,h，这个算我写的一个失误，但是没有影响，因为generate_anchor_base只是生成先验框（还没有映射到每一个点上），高和宽的顺序并不重要，一般先验框都会关于y=x这个线有一个对称。

**Comment by qiushenjie** [comment]
OK, 多谢
