### ISSUE TITLE
关于RPN模块的输出

### ISSUE THREAD

**Issue by yangjiangeyjg** [bubbliiiing/faster-rcnn-pytorch#29]
RPN的输出rois, roi_indices的含义分别是什么呢？shape分别是多少？初学者比较模糊，希望作者讲一下，十分感谢。
我看到在后续的ROI池化及进一步分类的网络中输入只用到rois和roi_indices，而不是rpn_locs和 rpn_scores。

**Comment by bubbliiiing** [comment]
既然都用pytorch了，你可以直接print出它的shape，就是roi区域的建议框位置和对应的batch序号吧
