### ISSUE TITLE
关于roi pool size的问题

### ISSUE THREAD

**Issue by lehaifeng000** [bubbliiiing/faster-rcnn-pytorch#57]
请问为什么backbone为vgg的时候roi pool size等于7，但是用resnet50的时候roi pool size设置的是14，这个有什么说法么？

**Comment by bubbliiiing** [comment]
这个好像设计的时候就是这样的，应该和网路结构比较相关，resnet50用最后一个layer来进行分类回归

**Comment by lehaifeng000** [comment]
> 这个好像设计的时候就是这样的，应该和网路结构比较相关，resnet50用最后一个layer来进行分类回归

我看了下高星的几个源码，resnet默认的roi pool size默认也是7，两个尺寸都测试过了map似乎没有什么变化。
但是源码里有一项resnet.max_pool的布尔值变量，为True时pool size为14。和vgg对比了一下发现vgg的head没有max pool，而resnet的head(最后一个layer)里做了一个下采样，所以是不是可以认为，resnet做roi head的时候，由于head会做下采样，因此roi pool的size从7升到14，然后14*14的rois经过head下采样后尺寸为7*7，后续和vgg就一致了？

**Comment by bubbliiiing** [comment]
嗯，可以这么理解，因为vgg已经直接下采样到了7，后面直接就分类和回归了，而resnet50的layer4还有一次下采样，所以14
