### ISSUE TITLE
兄弟，你这代码有问题的

### ISSUE THREAD

**Issue by buaacarzp** [bubbliiiing/faster-rcnn-pytorch#7]
你的代码有问题的，你训练的数据竟然不是gt对anchor的偏移量，这让我很吃惊！ 你是怎么做到的？

**Comment by bubbliiiing** [comment]
什么意思

**Comment by buaacarzp** [comment]
> 什么意思

你的train代码中喂入的应该是anchor对gt的偏移量，但是你喂入的直接是bbox和img

**Comment by bubbliiiing** [comment]
你没看到里面有编码的过程？

**Comment by buaacarzp** [comment]
> 你没看到里面有编码的过程？

哪里有编码啊？

**Comment by bubbliiiing** [comment]
trainer.py、utils/utils.py，你看的不够仔细

**Comment by buaacarzp** [comment]
> trainer.py、utils/utils.py，你看的不够仔细

我没有看到你做差 你可以自己看一下 你输入到rpn的是什么

**Comment by bubbliiiing** [comment]
输入到rpn的是共享特征层

**Comment by bubbliiiing** [comment]
rpn的输出会和网络应该有的结果对比

        # 计算建议框网络的loss值#
        rpn_loc_loss = _fast_rcnn_loc_loss(rpn_loc,
                                    gt_rpn_loc,
                                    gt_rpn_label.data,
                                    self.rpn_sigma)
        rpn_cls_loss = F.cross_entropy(rpn_score, gt_rpn_label.cuda(), ignore_index=-1)

**Comment by bubbliiiing** [comment]
loc = bbox2loc(anchor, bbox[argmax_ious])是编码

**Comment by bubbliiiing** [comment]
你觉得是哪个地方缺了吗

**Comment by buaacarzp** [comment]
> trainer.py、utils/utils.py，你看的不够仔细
你回归的是

> 你觉得是哪个地方缺了吗

我仔细了看了一遍又一遍，我不知道是我的理解有错误还是你的实现有问题:
```
        gt_rpn_loc, gt_rpn_label = self.anchor_target_creator(
            bbox.cpu().numpy(),
            anchor,
            img_size) #loc, label
```
我认为输入到rpn中数据应该是提前将anchor和gt做差值喂入网络，可是你输入到rpn的是共享层的特征，你的做差是竟然是在rpn输出后再去根据anchor对gt做偏移，我需要看下其他人的，然后再和你讨论下。

**Comment by bubbliiiing** [comment]
期待你开源上传将anchor和gt做差值喂入rpn的库，我再去学习一下，不过也不会将anchor和gt做差值，应该是将预测结果和gt做差值

**Comment by buaacarzp** [comment]
> 期待你开源上传将anchor和gt做差值喂入rpn的库，我再去学习一下，不过也不会将anchor和gt做差值，应该是将预测结果和gt做差值

兄弟，昨天是我理解错了！ 我一直以为的是输入到网络中的gt和anchor的差值，然后loss是让这两个差值最小化！ 原来是网络的输出与 （gt-anchor） 做loss，谢谢了，兄弟！ 我还有个问题想问下你，我一直不理解为什么classfier层的regression bbox回归的通道数是class_nums*4,你能详细的解释下吗？为什么要对每个分类做回归预测啊，直接回归不行吗？

**Comment by bubbliiiing** [comment]
可以，但是原版是对每个类进行回归，问题不大
