### ISSUE TITLE
预训练模型map 高于您的说明

### ISSUE THREAD

**Issue by chi0612** [bubbliiiing/faster-rcnn-pytorch#90]
我按照您的方法测试 voc_weights_resnet map可以达到80.35
voc_weights_vgg map达到77.36 高于您的描述 请问是什么原因

**Comment by bubbliiiing** [comment]
我提供的数据集？你自己重新划分了吗？

**Comment by chi0612** [comment]
没有重新划分，就是你的划分方式，只是生成了train.txt和val.txt



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月17日(周三) 晚上10:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bubbliiiing/faster-rcnn-pytorch] 预训练模型map 高于您的说明 (Issue #90)




 
我提供的数据集？你自己重新划分了吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bubbliiiing** [comment]
看看你的测试集，都有什么

**Comment by chi0612** [comment]
[2007_val.txt](https://github.com/bubbliiiing/faster-rcnn-pytorch/files/7555936/2007_val.txt)

**Comment by bubbliiiing** [comment]
很明显……你voc_annotation=0的时候运行了一遍= =

**Comment by chi0612** [comment]
如何是正确的 能麻烦您提供一下吗 我怕再次运行的还是不对

**Comment by chi0612** [comment]
我再把您的数据集划分下载一下 然后重新生成吧 谢谢您了

**Comment by chi0612** [comment]
> 很明显……你voc_annotation=0的时候运行了一遍= =
非常抱歉 但是我又重新下载了您的数据集 进行了VOC mode=2的划分 结果与我上传给您的文件完全一致 且vgg测试结果仍为77.36 这真的很困扰我

**Comment by chi0612** [comment]
> 看看你的测试集，都有什么

[test.txt](https://github.com/bubbliiiing/faster-rcnn-pytorch/files/7559342/test.txt)

**Comment by bubbliiiing** [comment]
你之前的map_out删了吗

**Comment by chi0612** [comment]
> 你之前的map_out删了吗

我用了随机数每次都创建新的map_out文件夹 结果都一样 
![微信图片_20211118224721](https://user-images.githubusercontent.com/56866907/142437959-15bb6bd9-8258-4de3-8fe8-2133f0061dd4.png)
![微信图片_20211118224850](https://user-images.githubusercontent.com/56866907/142437966-0d803487-247b-47ff-a97d-bb98ff2aadfb.png)

**Comment by bubbliiiing** [comment]
随机数？
没听懂
把你的map_out打包发给我把。bubbliiiing@qq.com，我自己也测一遍

**Comment by bubbliiiing** [comment]
噢噢，看到你的随机数了，你打包发给我吧

**Comment by chi0612** [comment]
发您了 麻烦了

**Comment by bubbliiiing** [comment]
妈的出问题了……我自己测出来比你的还高

**Comment by bubbliiiing** [comment]
我倒是记得一个月前我重新训练了一次……

**Comment by bubbliiiing** [comment]
但是我一直印象中没提高

**Comment by bubbliiiing** [comment]
79.17% = aeroplane AP   ||      score_threhold=0.5 : F1=0.66 ; Recall=76.84% ; Precision=57.18%
84.54% = bicycle AP     ||      score_threhold=0.5 : F1=0.70 ; Recall=85.16% ; Precision=59.18%
78.32% = bird AP        ||      score_threhold=0.5 : F1=0.66 ; Recall=81.05% ; Precision=55.36%
64.52% = boat AP        ||      score_threhold=0.5 : F1=0.49 ; Recall=80.61% ; Precision=35.10%
60.84% = bottle AP      ||      score_threhold=0.5 : F1=0.50 ; Recall=69.72% ; Precision=38.70%
86.23% = bus AP         ||      score_threhold=0.5 : F1=0.68 ; Recall=87.79% ; Precision=55.49%
88.96% = car AP         ||      score_threhold=0.5 : F1=0.69 ; Recall=89.68% ; Precision=56.27%
90.85% = cat AP         ||      score_threhold=0.5 : F1=0.72 ; Recall=91.90% ; Precision=58.54%
56.82% = chair AP       ||      score_threhold=0.5 : F1=0.47 ; Recall=66.14% ; Precision=37.01%
82.87% = cow AP         ||      score_threhold=0.5 : F1=0.69 ; Recall=88.52% ; Precision=55.96%
72.58% = diningtable AP         ||      score_threhold=0.5 : F1=0.56 ; Recall=81.55% ; Precision=42.53%
86.28% = dog AP         ||      score_threhold=0.5 : F1=0.64 ; Recall=92.43% ; Precision=48.76%
88.19% = horse AP       ||      score_threhold=0.5 : F1=0.72 ; Recall=88.79% ; Precision=60.23%
84.23% = motorbike AP   ||      score_threhold=0.5 : F1=0.71 ; Recall=84.92% ; Precision=61.06%
83.75% = person AP      ||      score_threhold=0.5 : F1=0.63 ; Recall=88.23% ; Precision=49.04%
44.66% = pottedplant AP         ||      score_threhold=0.5 : F1=0.39 ; Recall=62.71% ; Precision=28.69%
81.84% = sheep AP       ||      score_threhold=0.5 : F1=0.66 ; Recall=84.30% ; Precision=54.84%
71.33% = sofa AP        ||      score_threhold=0.5 : F1=0.59 ; Recall=82.43% ; Precision=45.39%
84.80% = train AP       ||      score_threhold=0.5 : F1=0.67 ; Recall=89.36% ; Precision=53.50%
78.46% = tvmonitor AP   ||      score_threhold=0.5 : F1=0.67 ; Recall=80.84% ; Precision=57.91%
mAP = 77.46%

**Comment by chi0612** [comment]
难道数据泄露了。。

**Comment by bubbliiiing** [comment]
泄露指的是？
我训练的数据和测试的数据划分的很清楚的，这不会混起来

**Comment by bubbliiiing** [comment]
混起来就不会这么低了

**Comment by chi0612** [comment]
只要数据没混 那就应该没问题 最多是map计算出问题了

**Comment by bubbliiiing** [comment]
我看看另一个电脑上多少

**Comment by bubbliiiing** [comment]
这个权值的修改时间是1月……我没有重训练……我看看是不是因为nms_iou的值调整了的远古

**Comment by chi0612** [comment]
我用frcnn.py里的参数confidence 0.5 nms_iou0.3测是73.62

**Comment by chi0612** [comment]
您的这个77.36比论文里的73.2好了太多

**Comment by bubbliiiing** [comment]
我仔细看聊一下，应该是我改了预测解码的过程，所以效果好一些了

**Comment by bubbliiiing** [comment]
论文里是07而非07+12

**Comment by chi0612** [comment]
![image](https://user-images.githubusercontent.com/56866907/142445456-49c6c01a-317d-4215-adaa-2e4d4bea2a48.png)
这个应该就是07+12吧

**Comment by chi0612** [comment]
> 我仔细看聊一下，应该是我改了预测解码的过程，所以效果好一些了

这部分您能指点一下是哪块吗 我仔细研究一下

**Comment by bubbliiiing** [comment]
别慌……我先看看我之前的代码能出来多少

**Comment by bubbliiiing** [comment]
我的远古代码我还保留着，这个代码一个月左右前有个大改

**Comment by chi0612** [comment]
10.14号那天你刚传完注释版十分钟，我发现了你的库😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月18日(周四) 晚上11:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [bubbliiiing/faster-rcnn-pytorch] 预训练模型map 高于您的说明 (Issue #90)




 
我的远古代码我还保留着，这个代码一个月左右前有个大改
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bubbliiiing** [comment]
我也不知道……就算是之前的代码理论上也比论文高，可能论文之前的参数调节的不是很好吧？

**Comment by bubbliiiing** [comment]
毕竟很早的文章了

**Comment by bubbliiiing** [comment]
yolo3最开始的map和u版本的yolo3也没法比不是

**Comment by chi0612** [comment]
有道理，你那边训练一次收敛需要多少个epoch，我也想自己训练一下

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月18日(周四) 晚上11:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [bubbliiiing/faster-rcnn-pytorch] 预训练模型map 高于您的说明 (Issue #90)




 
yolo3最开始的map和u版本的yolo3也没法比不是
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bubbliiiing** [comment]
时间很长……就是从主干开始，按默认训练完

**Comment by bubbliiiing** [comment]
我测试了一下代码，map的计算代码应该是无误的，应该是我自己修改了解码方式，但是我没有重测map

**Comment by bubbliiiing** [comment]
之前的库如果你要的话，我可以发给你，你对比二者差别？

**Comment by bubbliiiing** [comment]
差别蛮大的…

**Comment by chi0612** [comment]
***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月18日(周四) 晚上11:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [bubbliiiing/faster-rcnn-pytorch] 预训练模型map 高于您的说明 (Issue #90)




 
之前的库如果你要的话，我可以发给你，你对比二者差别？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bubbliiiing** [comment]
你的邮件……刚发给我了……我知道……你给我发了你的map_out

**Comment by chi0612** [comment]
哈哈哈好的，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月18日(周四) 晚上11:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [bubbliiiing/faster-rcnn-pytorch] 预训练模型map 高于您的说明 (Issue #90)




 
你的邮件……刚发给我了……我知道……你给我发了你的map_out
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bubbliiiing** [comment]
第一封发了个空……只发了代码部分
model_data一样的

**Comment by bubbliiiing** [comment]
过去的代码比较乱，看看就好

**Comment by chi0612** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月18日(周四) 晚上11:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [bubbliiiing/faster-rcnn-pytorch] 预训练模型map 高于您的说明 (Issue #90)




 
过去的代码比较乱，看看就好
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by misck** [comment]
> > 你之前的map_out删了吗
> 
> 我用了随机数每次都创建新的map_out文件夹 结果都一样 ![微信图片_20211118224721](https://user-images.githubusercontent.com/56866907/142437959-15bb6bd9-8258-4de3-8fe8-2133f0061dd4.png) ![微信图片_20211118224850](https://user-images.githubusercontent.com/56866907/142437966-0d803487-247b-47ff-a97d-bb98ff2aadfb.png)

你好，我想问问你图里的每个类别的AP是怎么出来的
